### ISSUE TITLE
compatibility with PHP 8.1

### ISSUE THREAD

**Issue by mark-faulk** [mithunsatheesh/php-drpc#4]
In order to get this to work in PHP 8.1, I had to change line 3 in DRPC.php from:

`spl_autoload_register(function ($classname) {`

to:

`function __autoload($classname) {`

**Comment by mithunsatheesh** [comment]
Thanks Mark. You can raise a pull request if you think it can help more people.

**Comment by mark-faulk** [comment]
Thank you Mithun. I tried to push my branch up but I got this error:

`ERROR: Permission to mithunsatheesh/php-drpc.git denied to mark-faulk.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.`

Could you please give me permission?

**Comment by mithunsatheesh** [comment]
Hi @mark-faulk Please raise a Pull Request. Will review and merge it into the code base.
