### ISSUE TITLE
Publish package request

### ISSUE THREAD

**Issue by KasonBraley** [mithunsatheesh/php-drpc#8]
Now that the library is installable via Composer, it would be best if the package was available on [packagist](https://packagist.org/). This would allow users to [only have to run](https://getcomposer.org/doc/02-libraries.md#publishing-to-packagist) `composer require mithunsatheesh/php-drpc` to install the library. 

I understand if you wouldn't want to go through this trouble. If that's the case, I can update the README to include the necessary [additional instructions](https://getcomposer.org/doc/02-libraries.md#publishing-to-a-vcs) to point to this repository to be able to install.

Another thing to complete is versioning. This is [best done with git tags](https://getcomposer.org/doc/02-libraries.md#library-versioning), but it could also be done without version control by adding the version straight into the composer.json.

Let me know what you think, thanks!

**Comment by mithunsatheesh** [comment]
@KasonBraley I have added contributor access to the package if that helps to create tags for versioning. Agree with the suggestions here. Let me see the steps to publish this to packagist. I'm new to it.

**Comment by KasonBraley** [comment]
Thank you. Sounds good, I am also new to packagist.

**Comment by mithunsatheesh** [comment]
Its now published in packagist as seen here: https://packagist.org/packages/mithunsatheesh/php-drpc.

**Comment by KasonBraley** [comment]
Awesome! Do you have any preferences on the initial version to use? 1.0, 0.1.0, 0.0.1, etc. ?

**Comment by mithunsatheesh** [comment]
Anything works.
